//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDP_02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DP_LoaiSanPham
    {
        public int LoaiSanPham { get; set; }
        public string MaLoaiSanPham { get; set; }
        public string TenLoaiSanPham { get; set; }
        public int NguoiTao { get; set; }
        public System.DateTime NgayTao { get; set; }
        public Nullable<int> NguoiSua { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public Nullable<int> NguoiXoa { get; set; }
        public Nullable<System.DateTime> NgayXoa { get; set; }
        public bool IsDel { get; set; }
        public Nullable<int> NguoiNhap { get; set; }
        public string IPNhap { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string MayNhap { get; set; }
        public string IPSua { get; set; }
        public string MaySua { get; set; }
        public string IPXoa { get; set; }
        public string MayXoa { get; set; }
        public Nullable<bool> IsCoSize { get; set; }
        public string TenLoaiSanPham_EN { get; set; }
        public string TenLoaiSanPham_JP { get; set; }
    }
}
