//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDP_02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DP_DonViTinh
    {
        public int DonViTinh { get; set; }
        public string TenDonViTinh { get; set; }
    }
}
