//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDP_02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DP_Size
    {
        public int Size { get; set; }
        public string MaSize { get; set; }
        public int LoaiSanPham { get; set; }
        public Nullable<int> NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> NguoiSua { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public Nullable<int> NguoiXoa { get; set; }
        public Nullable<System.DateTime> NgayXoa { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public Nullable<int> STTSize { get; set; }
    }
}
