//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDP_02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NS_DP_PhieuNhapHang
    {
        public int PhieuNhapHang { get; set; }
        public string MaPhieuNhapHang { get; set; }
        public string TenPhieuNhapHang { get; set; }
        public int NguoiDatHang { get; set; }
        public System.DateTime NgayDatHang { get; set; }
        public Nullable<int> NguoiDuyet { get; set; }
        public Nullable<System.DateTime> NgayDuyet { get; set; }
        public Nullable<int> TrangThaiDuyet { get; set; }
        public string LyDo { get; set; }
        public string GhiChu { get; set; }
        public int KhoNhan { get; set; }
        public Nullable<decimal> TongThanhToan { get; set; }
        public Nullable<int> TongSLMua { get; set; }
        public Nullable<int> TongSLDaNhap { get; set; }
        public int NguoiTao { get; set; }
        public System.DateTime NgayTao { get; set; }
        public Nullable<int> NguoiSua { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public Nullable<int> NguoiXoa { get; set; }
        public Nullable<System.DateTime> NgayXoa { get; set; }
        public bool IsDel { get; set; }
        public Nullable<bool> IsHoanThanh { get; set; }
        public Nullable<int> NhaCungCap { get; set; }
    }
}
