//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDP_02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NS_DP_PhieuDeNghi_ChiTiet
    {
        public int ID { get; set; }
        public int PhieuDeNghi { get; set; }
        public Nullable<int> NhanSu { get; set; }
        public int SanPham { get; set; }
        public Nullable<int> Size { get; set; }
        public int SoLuong { get; set; }
        public int LyDoCapPhat { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> DonViTinh { get; set; }
        public Nullable<int> SoLuongDaNhan { get; set; }
        public Nullable<int> PhieuDeNghi_CaNhan_ChiTiet { get; set; }
        public Nullable<int> TinhChatDongPhuc { get; set; }
        public Nullable<int> TrangThaiDuyet { get; set; }
        public Nullable<int> NguoiDuyet { get; set; }
        public Nullable<System.DateTime> NgayDuyet { get; set; }
        public string LyDoTuChoi { get; set; }
    }
}
