//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDP_02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NS_DP_SanPham
    {
        public int SanPham { get; set; }
        public string TenSanPham { get; set; }
        public int LoaiSanPham { get; set; }
        public Nullable<int> DonViTinh { get; set; }
        public string QuyCachDoi { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public Nullable<int> NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> NguoiSua { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public Nullable<int> NguoiXoa { get; set; }
        public Nullable<System.DateTime> NgayXoa { get; set; }
        public Nullable<int> GioiTinh { get; set; }
        public Nullable<int> SanPhamLienKet { get; set; }
        public string TenSanPham_EN { get; set; }
        public string TenSanPham_JP { get; set; }
    }
}
