//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDP_02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NS_DP_SanPham_TinhChatDongPhuc
    {
        public int ID { get; set; }
        public int SanPham { get; set; }
        public Nullable<int> TinhChatDongPhuc { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<int> NhaCungCap { get; set; }
    }
}
