//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDP_02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NS_DP_PhieuDeNghi_CaNhan
    {
        public int PhieuDeNghi_CaNhan { get; set; }
        public string MaPhieuDeNghi_CaNhan { get; set; }
        public int NguoiDeNghi { get; set; }
        public System.DateTime NgayDeNghi { get; set; }
        public string GhiChu { get; set; }
        public int NguoiTao { get; set; }
        public System.DateTime NgayTao { get; set; }
        public Nullable<int> NguoiSua { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public Nullable<int> NguoiXoa { get; set; }
        public Nullable<System.DateTime> NgayXoa { get; set; }
        public Nullable<int> NguoiDuyet { get; set; }
        public Nullable<System.DateTime> NgayDuyet { get; set; }
        public Nullable<int> TrangThaiDuyet { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public Nullable<bool> IsNhanVienMoi { get; set; }
        public Nullable<int> LyDoCapPhat { get; set; }
        public string LyDoTuChoi { get; set; }
        public Nullable<int> TrangThaiDuyet2 { get; set; }
        public Nullable<int> NguoiDuyet2 { get; set; }
        public Nullable<System.DateTime> NgayDuyet2 { get; set; }
        public Nullable<int> TrangThaiDuyet3 { get; set; }
        public Nullable<int> NguoiDuyet3 { get; set; }
        public Nullable<System.DateTime> NgayDuyet3 { get; set; }
        public Nullable<bool> IsHoanThanh { get; set; }
    }
}
