//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDP_02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NS_NhanSu
    {
        public int NhanSu { get; set; }
        public string MaNhanSu { get; set; }
        public string HoDem { get; set; }
        public string Ten { get; set; }
        public Nullable<int> CapBac { get; set; }
        public Nullable<int> ChucDanh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DienThoaiDiDong1 { get; set; }
        public Nullable<int> GioiTinh { get; set; }
        public string SoCMND { get; set; }
        public Nullable<System.DateTime> CMND_NgayCap { get; set; }
        public string CMND_NoiCap { get; set; }
        public string TaiKhoan1 { get; set; }
        public string NganHang1 { get; set; }
        public string TaiKhoan2 { get; set; }
        public string NganHang2 { get; set; }
        public Nullable<int> TrinhDoHocVan { get; set; }
        public Nullable<int> ChuyenNganh { get; set; }
        public Nullable<int> TruongHoc { get; set; }
        public Nullable<int> NamTotNghiep { get; set; }
        public Nullable<int> TinhTrangHonNhan { get; set; }
        public string Email { get; set; }
        public string Email_CaNhan { get; set; }
        public string HoKhauThuongTru { get; set; }
        public string DiaChiLienLac { get; set; }
        public string HoKhauTamTru { get; set; }
        public Nullable<int> TinhThanhPho { get; set; }
        public Nullable<int> QuanHuyen { get; set; }
        public Nullable<int> PhuongXa { get; set; }
        public Nullable<System.DateTime> NgayChinhThuc { get; set; }
        public Nullable<System.DateTime> NgayNghiViec { get; set; }
        public Nullable<int> DanToc { get; set; }
        public Nullable<int> QuocTich { get; set; }
        public Nullable<int> TonGiao { get; set; }
        public bool IsThamGiaBHXH { get; set; }
        public bool IsThamGiaBHYT { get; set; }
        public bool IsThamGiaBHTN { get; set; }
        public bool IsThamGiaCongDoan { get; set; }
        public bool IsDel { get; set; }
        public Nullable<System.DateTime> NgayDel { get; set; }
        public string LinkHinh { get; set; }
        public string GhiChu { get; set; }
    }
}
